version: "3.1"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - "8081:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    #volumes:
    #    - <YOUR LOCAL PATH>:/var/lib/mysql
    ports:
      - "5506:3306"
    restart: unless-stopped
